name: smart_id_scanner
description: A Flutter plugin for scanning ID documents using ML Kit
version: 0.0.1
homepage: https://github.com/mubashirspam/smart_id_scanner

environment:
  sdk: '>=2.19.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.1
  google_mlkit_text_recognition: ^0.15.0
  google_mlkit_commons: ^0.11.0
  image: ^4.0.17
  intl: ^0.19.0
  permission_handler: ^11.0.2
  path_provider: ^2.1.5
  image_picker: ^1.1.2
  # camerawesome: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

platforms:
  android:
  ios:

# This declares the plugin structure
# flutter:
#   plugin:
#     platforms:
#       android:
#         package: com.mubashir.smart_id_scanner
#         pluginClass: SmartIdScannerPlugin
#       ios:
#         pluginClass: SmartIdScannerPlugin